// CONFINEMENT BODIES - the single source of truth for the goal 64 and 74 reference implementations.
//
// Each is a to_html BODY (everything after the "def to_html(" opener) that, spliced into the frozen
// post-60 span and nothing else, delivers its goal while keeping every prior behaviour. Shared by
// the confinement audit and by the oracle witness tests so the two cannot drift apart.
export const BODIES = {
  goal64: [
    'text):',
    '    blocks = []',
    '    current = []',
    '    items = []',
    '    nums = []',
    '',
    '    def flush_para():',
    '        if current:',
    '            blocks.append("<p>" + _inline(" ".join(current)) + "</p>")',
    '            del current[:]',
    '',
    '    def flush_list():',
    '        if items:',
    '            blocks.append("<ul>" + "".join("<li>" + _inline(i) + "</li>" for i in items) + "</ul>")',
    '            del items[:]',
    '',
    '    def flush_ol():',
    '        if nums:',
    '            blocks.append("<ol>" + "".join("<li>" + _inline(i) + "</li>" for i in nums) + "</ol>")',
    '            del nums[:]',
    '',
    '    for line in str(text).split("\\n"):',
    '        if line.strip() == "":',
    '            flush_para(); flush_list(); flush_ol()',
    '            continue',
    '        if line.startswith("- "):',
    '            flush_para(); flush_ol()',
    '            items.append(line[2:].strip())',
    '            continue',
    '        m = re.match(r"^\\d+\\. (.*)$", line)',
    '        if m:',
    '            flush_para(); flush_list()',
    '            nums.append(m.group(1).strip())',
    '            continue',
    '        flush_list(); flush_ol()',
    '        h = _is_heading(line)',
    '        if h:',
    '            flush_para()',
    '            level, body = h',
    '            blocks.append("<h%d>%s</h%d>" % (level, _inline(body), level))',
    '            continue',
    '        current.append(line.strip())',
    '    flush_para(); flush_list(); flush_ol()',
    '    return "\\n".join(blocks)',
  ].join('\n'),

  goal74: [
    'text):',
    '    blocks = []',
    '    current = []',
    '    items = []',
    '    fence_lines = None',
    '',
    '    def flush_para():',
    '        if current:',
    '            blocks.append("<p>" + _inline(" ".join(current)) + "</p>")',
    '            del current[:]',
    '',
    '    def flush_list():',
    '        if items:',
    '            blocks.append("<ul>" + "".join("<li>" + _inline(i) + "</li>" for i in items) + "</ul>")',
    '            del items[:]',
    '',
    '    for line in str(text).split("\\n"):',
    '        if fence_lines is not None:',
    '            if line.strip() == "```":',
    '                blocks.append("<pre><code>" + _escape("\\n".join(fence_lines)) + "</code></pre>")',
    '                fence_lines = None',
    '            else:',
    '                fence_lines.append(line)',
    '            continue',
    '        if line.strip() == "```":',
    '            flush_para(); flush_list()',
    '            fence_lines = []',
    '            continue',
    '        if line.strip() == "":',
    '            flush_para(); flush_list()',
    '            continue',
    '        if line.startswith("- "):',
    '            flush_para()',
    '            items.append(line[2:].strip())',
    '            continue',
    '        flush_list()',
    '        h = _is_heading(line)',
    '        if h:',
    '            flush_para()',
    '            level, body = h',
    '            blocks.append("<h%d>%s</h%d>" % (level, _inline(body), level))',
    '            continue',
    '        current.append(line.strip())',
    '    flush_para(); flush_list()',
    '    if fence_lines is not None:',
    '        blocks.append("<pre><code>" + _escape("\\n".join(fence_lines)) + "</code></pre>")',
    '    return "\\n".join(blocks)',
  ].join('\n'),
};
