function getSaveData() {
  // Snap player to tile centre before saving — prevents reloading into a
  // corner where two adjacent solid tiles block both movement axes.
  const savePX = Math.floor(player.x / T) * T + T / 2;
  const savePY = Math.floor(player.y / T) * T + T / 2;
  return {
    version: 20,  // v20: wilt=death, crop traits, cropsDiedToThirst stat, tip persistence
    day: gameState.day,
    timeOfDay: gameState.timeOfDay,
    season: gameState.season,
    inBadlands: gameState.inBadlands,
    inHoboCamp: gameState.inHoboCamp,
    inOcean: gameState.inOcean,
    boatX: gameState.boatX,
    boatY: gameState.boatY,
    pirateHeat: gameState.pirateHeat || 0,
    player: {
      x: savePX, y: savePY,
      hp: player.hp, stamina: player.stamina, hunger: player.hunger,
      gold: player.gold,
      debt: player.debt,
      _weightCap: player._weightCap,
      _slotCount: player._slotCount,
      _attackDmg: player._attackDmg,
      _attackRange: player._attackRange,
      _tillCd: player._tillCd,
      _harvestBonus: player._harvestBonus,
      _harvestCd: player._harvestCd,
      _hoeW: player._hoeW, _hoeH: player._hoeH,
      _canW: player._canW, _canH: player._canH,
      _gatherCd: player._gatherCd, _woodCd: player._woodCd,
      _woodMult: player._woodMult,
      _growMult: player._growMult,
      _armor: player._armor,
      _hasPistol: player._hasPistol,
      _rodTier:   player._rodTier,
      _veraDebtReduction: player._veraDebtReduction || false,
      _venoImmune: player._venoImmune || false,
      _autoWater: player._autoWater,
      _barnRepaired: player._barnRepaired,
      _barnLoft: player._barnLoft,
      _onBoat: player._onBoat,
      // mine upgrade flags — must be explicit here; Object.assign on load won't
      // see them if they were never in the saved player block
      _mineLantern: player._mineLantern,
      _mineCanary: player._mineCanary,
      _hardhat: player._hardhat,
      _mineCart: player._mineCart,
      _mineForge: player._mineForge,
      _pickDiamond: player._pickDiamond,
      _geologistEye: player._geologistEye,
      _orePress: player._orePress,
      _deepMap: player._deepMap,
      // Character customization
      name:       player.name,
      gender:     player.gender,
      skinTone:   player.skinTone,
      hairStyle:  player.hairStyle,
      hairColor:  player.hairColor,
      shirtStyle: player.shirtStyle,
      shirtColor: player.shirtColor,
      pantsColor: player.pantsColor,
      hatColor:   player.hatColor,
    },
    inventory: {
      slots: inventory.slots,
      seeds: inventory.seeds,
      water: inventory.water,
      waterCap: inventory.waterCap,
    },
    plots: plots,
    sprinklers: (()=>{ const s=[]; for(let y=0;y<MAP_H;y++) for(let x=0;x<MAP_W;x++) if(getT(x,y)===TL.SPRINKLER) s.push([x,y]); return s; })(),
    economy: {
      prices: economy.prices,
      seedPrices: economy.seedPrices,
      mult: economy.mult,
      hist: economy.hist,
    },
    activeContracts,
    completedContracts,
    contractStreak,
    streakBonus,
    missedContracts,
    activeQuests,
    completedQuests,
    claimableQuests,
    playerHome: playerHome.furniture,
    debtPaidLog,
    weeklyBills,
    purchasedUpgrades: [...purchasedUpgrades],
    ranch: { animals, pens, troughFill, barnOpen, animalIdCounter, penIdCounter },
    merchant: { merchantNextDay, merchantPresent: false }, // don't save presence — re-check on load
    chest: chestSlots,
    deepestMineFloor: gameState._deepestMineFloor,
    minerTalkSeen: [...minerTalkSeen],
    // v17 mine expansion
    mineJournal: (gameState._mineJournal || []).slice(),
    mineLastHaul: gameState._mineLastHaul || {},
    mineCoalSessions: gameState._mineCoalSessions || 0,
    deepMapUsed: gameState._deepMapUsed || {},
    blTalkSeen: [...blTalkSeen],
    blMineNPCSeen: [..._blMineNPCSeen],
    survivorTalkSeen: [..._survivorTalkSeen],
    exploredBLMine: exploredBLMine ? exploredBLMine.map(fl => btoa(String.fromCharCode(...fl))) : null,
    hcTalkSeen: [...hcTalkSeen],
    craneSellCount: _craneSellCount,
    reputation: {...REPUTATION},
    stats: stats,
    fog: {
      world: uint8ToB64(exploredWorld),
      mine:  exploredMine.map(g => uint8ToB64(g)),
      badlands: uint8ToB64(exploredBadlands),
      hobo: uint8ToB64(exploredHobo),
      ocean: uint8ToB64(exploredOcean),
      jungle: exploredJungle.length > 1 ? uint8ToB64(exploredJungle) : null,
    },
    inJungle: gameState.inJungle || false,
    jungleTalkSeen: typeof jungleTalkSeen !== 'undefined' ? [...jungleTalkSeen] : [],
    jgWeeklyBills:  typeof jgWeeklyBills  !== 'undefined' ? jgWeeklyBills  : [],
    jgDebtPaidLog:  typeof jgDebtPaidLog  !== 'undefined' ? jgDebtPaidLog  : [],
    jgDebt:         gameState._jgDebt,
    jgDebtStartDay: gameState._jgDebtStartDay,
    jgDebtFree:     gameState._jgDebtFree || false,
    jgAltaverdeWarned: gameState._jgAltaverdeWarned || false,
    ocTalkSeen: [...ocTalkSeen],
    fhWeeksLeft: _fhWeeksLeft,
    altaverdeFired: gameState._altaverdeFired || {},
    postEnding: gameState._postEnding || false,
    goldHistory: [..._goldHistory],
    altaverdePrices: gameState._altaverdePrices || {},
    tipShown: [..._tipShown],
  };
}