function _takeJournalSnapshot() {
  return {
    day:           gameState.day,
    gold:          player.gold,
    totalKills:    stats.totalKills,
    cropsHarvested: stats.totalCropsHarvested,
    plantingsDone: stats.plantingsDone,
    tilesWatered:  stats.tilesWatered,
    totalOreMined: stats.totalOreMined,
    totalFishCaught: stats.totalFishCaught,
    junkBootsFished: stats.junkBootsFished,
    woodChopped:   stats.woodChopped,
    stoneGathered: stats.stoneGathered,
    herbsGathered: stats.herbsGathered,
    totalItemsCrafted: stats.totalItemsCrafted,
    debtRepaid:    stats.debtRepaid,
    contractsCompleted: stats.contractsCompleted,
    inBadlands:    gameState.inBadlands,
    inMine:        gameState.inMine,
    inOcean:       gameState.inOcean,
    inHoboCamp:    gameState.inHoboCamp,
    season:        gameState.season || (typeof getCurrentSeason === 'function' ? getCurrentSeason()?.name : 'Unknown'),
    weekNumber:    typeof getWeekNumber === 'function' ? getWeekNumber(gameState.day) : 0,
    totalDebt:     typeof getTotalDebt === 'function' ? getTotalDebt() : 0,
    aliveAnimals:  typeof animals !== 'undefined' ? animals.filter(a => a.hp > 0).length : 0,
    productsCollected: stats.productsCollected || 0,
    cropsReady:    typeof plots !== 'undefined' ? Object.values(plots).filter(p => p.harvestReady).length : 0,
    cropsWilted:   typeof plots !== 'undefined' ? Object.values(plots).filter(p => p.wilted).length : 0,
    oreByType:     JSON.parse(JSON.stringify(stats.oreMinedByType || {})),
    fishByType:    JSON.parse(JSON.stringify(stats.fishCaught || {})),
    killsByType:   JSON.parse(JSON.stringify(stats.kills || {})),
    singingStones: stats.singingStonesFound || 0,
    deepestFloor:  gameState._deepestMineFloor || 0,
  };
}